<<<<<<< HEAD
sudo: true
language: node_js
node_js:
  - "4"
  - "5"
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"
- npm install
- npm install -g mocha babel@5
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start &
- sleep 3
- npm run test-e2e:crdv &
- sleep 3

script:
- npm run test
- npm run build
- npm run test-e2e
=======
sudo: false

language: node_js

node_js:
  - 6
  - 5
  - 4

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso

install:
  - export CXX="g++-4.8"
  - npm install
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run test-e2e
  - npm run package
>>>>>>> 9d0782912ae4100825089e1678a684966bedee59
